bpms:
  url: http://localhost:8080
dso:
  url: http://localhost:8081
form-management-provider:
  url: http://localhost:8082

server:
  port: 8888
  servlet:
    context-path: /user-task-management

ceph:
  http-endpoint: http://localhost:8100
  access-key: access-key
  secret-key: secret-key
  bucket: bucket