image:
  name: user-task-management
  version: latest
port: 8080
service:
  type: ClusterIP
  port: 8080
replicas: 1
appConfigMountPath: "/app/config"
cephSecretMountPath: "/app/secrets/ceph"
readinessPath: "/user-task-management/actuator/health/readiness"
livenessPath: "/user-task-management/actuator/health/liveness"

prometheus:
  endpoints:
    - scrapePath: "/user-task-management/actuator/prometheus"
      port: "{{ .Values.service.port }}"

ingress: # expose the service with a route or an ingress depending on platform type
  platform: openshift # openshift or kubernetes

ceph:
  bucketName: lowcode-form-data-storage

monitoring:
  namespace: openshift-monitoring

keycloak:
  realms:
    officer: officer-portal
    citizen: citizen-portal
    admin: admin
  certificatesEndpoint: /protocol/openid-connect/certs

deployProfile: prod

javaOpts: "-Xms512m -Xmx512m"