kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: authoriz-policy-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  rules:
    - from:
        - source:
            notRequestPrincipals:
              - '*'
      to:
        - operation:
            notPaths:
              - /{{ .Chart.Name }}/actuator/*
              - /{{ .Chart.Name }}/swagger
              - /{{ .Chart.Name }}/swagger-ui/*
              - /{{ .Chart.Name }}/v3/api-docs*
  action: DENY