{{- if eq .Values.ingress.platform "kubernetes" }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  rules:
    - host: user-task-mng-{{ .Values.cdPipelineName }}-{{ .Values.cdPipelineStageName }}.{{ .Values.dnsWildcard }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: {{ .Values.service.port }}
  {{- end }}
